travis:
  secure:
    BINSTAR_TOKEN: Y4YHVY6/L7LniMSLPH1DhT30JyVSLkMWo4urYg9OBpjh2TBtTX7lMUe8eL+Gr3A7WM3I2ARSuqf+h4bIuRkb3TrZIzfkSmTsdvYkIZf4E/yDuyfctVr5erQbjmDeyLDDEdEJ4f2ivDl+XmHVh1uEinxrHg6zn0Mfcnx69JeL04XETAvn543lM/U0kisV8jrGkd7kHDxtI8qZmHxDt9XjtCsrgtBsn1uXlHjWzBRf11XLePwoTHbLGE9xRh28IhnWWegX/QbbMGB4N+Ay1LnneGGsyVhc9y9ZUMieNKjVFItp+9mtfObIiORXTyaKIavWI5xHje8QR3B0AORWF0ZdrJmlkv04T9mhuxS1GAUZ4Rs7rZS2FF6igCZoEpDGzqk5s02lpWHaT6i7a19Ftk2ArOgs0qg30PvuuOYXWWeMABjtiGaNE7HchCrT3BC9+a5gBIicvo8X23JZZg8wUySvePP/jStD3tKgPUiJpik12CknnHhQc4Zh/TsIpcLTfmqzcCMuJGe3lcOr/DX5OCaMZsG+OvOlcPT9VLo5c1nXCBtcPLhY5jog/Q0N2ItFH0bE28Tuy5e2s5Qk9dIlyhKnMXnauBNSIkielcV8KR1Tl7pjRUaUIDZqjzV8K0NcfltD8uy7Mhl+rh9GmgurHbrg1UoT3odJRiQz4fOH21YgK38=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
