travis:
  secure:
    BINSTAR_TOKEN: b3BfpKjvD7bpL3MdNWKDMN4ArGWZfkSL70IAEnh7HYYtIcyDB7sytKxhYh84wHbbpvdkJqOtJC7SbdpXtcLnI4dA5Ah68jvvcaqYreLYVVGuSADK7vQvbrtHtFx/+sp2j3x4DKolm1ZXRVf3QXTJCxscuib0Y0y4RGmqKrlO5TIGpL4yZcQEVspNpCRWckEeqOyqajKEW0OU9G1mdTXTq0+OqhYJ6+nEukE6HENXyej0Oo9Cei+P3dBibLyN3TXHkP12yppQwZukuYBUlK4z3GDapoGILYtKX5Dd3NxXiwub6lU17q5lgZK6tbWW5VQf3iaFGEZ1YmYAE1qCJN3p3OaOkAbmtnu77sdZWGLR+OVGvYonRWgw2GoDP6QQN2wkEWGVXcFICCsoD3tffxA3IpFuvUwZ6icC4OfkZtKXshyQjebYJhUL1q3u+zpD7MZ4r+fFY+Uxi9GxsknbvjgcmyjrgA93lyrRCc0w8IgPjreB5mbzTXCjMrMWv5FSApsH0d4cmYHha7b968cp3cQn2Z1yl/f93JkJQBIv8y8cBgd7j4fZwdce3wj/1vxqsbHVirHwqkh9L3K0he9kCZTkHmzJHiqCUtpSaebcu09ZAQY4md6v+IH2wj0PDanOc1tmPwatQVLzjYSqjEyI+bSazUCsHNIM4dEnP9uxsWM2kfU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
